### ISSUE TITLE
Any active maintainers?

### ISSUE THREAD

**Issue by mvdan** [go-jira/jira#248]
I see little activity since last November, so I wonder if the project is actively maintained.

If not, is there a need for someone to adopt the project, or become a maintainer?

I have no reason to think that master is badly broken, but given that JIRA moves quite rapidly, I imagine it will break eventually. It also seems to be broken for Go modules, which would be a fairly easy fix: https://github.com/Netflix-Skunkworks/go-jira/issues/228#issuecomment-493908463

**Comment by coryb** [comment]
Hi @mvdan, as you correctly note there is very little activity on this project.  I use the tool daily for myself but have little time to review issues or pull-requests.

I am very open to adding maintainers for anyone who is interested in helping out.

**Comment by mvdan** [comment]
Thanks, good to hear. Are there any other active maintainers? If so, do you chat with them anywhere?

I too have started using this tool on a daily basis. There's some low-hanging fruit I'd like to help with, so I can get on that if you add me as a contributor. Are there any guidelines, e.g. not pushing straight to master?

**Comment by coryb** [comment]
In theory, you should have write access now, that should mean you can merge PRs as well.

Using the Netflix-Shunkworks org is a bit troublesome since there is automated management of users there, I don't actually have direct admin access to this repo anymore.  This means non Netflix employees cannot grant access to other users.  I am wondering long-term if we want to re-home this project to a different org, I think I could probably get it moved to `coryb/go-jira` then we could fork it back to `Netflix-Shunkworks/go-jira` for backwards compatibility and add a note to the README there.

There are no other active developers on this project, so no active chats.  I will create a #go-jira channel on gophers.slack.com and invite you there.

As for guidelines, I don't have many.  I think PRs are a good idea for most changes, you can tag me as a reviewer and I will try to look soon.  For really minor changes I think direct commits are fine.  I will follow the same process and tag you on PRs if you are up for it.

The code structure is definitely oddball, sorry.  It was basically "my first Go project",  so pretty bad.

Anyone else that finds this thread and is interested in contributing ... I would love help.  Join in to the #go-jira channel on gophers.slack.com.

**Comment by vanniktech** [comment]
I'm happy to review some PRs too.

**Comment by coryb** [comment]
Hey @vanniktech, great!  I have granted you push access, which should allow you to merge PRs.  

I am thinking we can setup PRs to require 1 reviewer to merge to master and I believe I can include you both as default reviewers.  I will look into setting that up.

**Comment by mvdan** [comment]
Thanks - I do have access. The #go-jira channel on slack will be very useful.

If the Netflix organisation can be a problem, moving it elsewhere seems fine. Honestly, anywhere seems good as long as there's no bus factor. For that reason, I think I'd prefer a dummy org like `github.com/go-jira` over anyone's personal account.

Also, I don't think a fork will be necessary. If I remember correctly, GitHub supports transferring repositories to organisations, and it should handle redirects properly. This shouldn't break `go get` I think, as the import path would remain being `gopkg.in` for now.

> The code structure is definitely oddball, sorry. It was basically "my first Go project", so pretty bad.

No worries - I've been in the same situation many times before. I mainly worry about good test coverage :)

Lastly, I don't know if setting up default reviewers is a good idea. I will spend some time on this project, but I don't think I'll be able to consistently commit time reviewing PRs.

**Comment by mvdan** [comment]
Also - the purpose of this issue is very much fulfilled, unless you want to keep it open to deal with follow-up ideas like creating an org.

**Comment by vanniktech** [comment]
> I am thinking we can setup PRs to require 1 reviewer to merge to master and I believe I can include you both as default reviewers. I will look into setting that up.

That sounds good.

> Also, I don't think a fork will be necessary. If I remember correctly, GitHub supports transferring repositories to organisations, and it should handle redirects properly.

They do - yes.

> Lastly, I don't know if setting up default reviewers is a good idea. I will spend some time on this project, but I don't think I'll be able to consistently commit time reviewing PRs.

I believe @coryb just wanted to set up that one review from someone with push access is given on a given PR.

**Comment by coryb** [comment]
A dedicated org would be great, github.com/go-jira already exists.  Most possible org names that I can think of seem to exist.  It mostly seems like people squatting on names that are unused.  I will ping the only commiter to github.com/go-jira and see if he would be open to allowing us to move there.

For reviewers, I was thinking that it would be better for everyone if we require 1 reviewer for each PR, not necessarily that you @mvdan must review everything.  I would feel more comfortable adding more contributors if I knew every PR was at least reviewed by someone before merging.  I know most of us will not have a lot of time to review, but hopefully we can eventually get enough contributors that someone is willing.

**Comment by mvdan** [comment]
Ah, apologies that I misunderstood. One reviewer per PR sounds fine :)

**Comment by coryb** [comment]
I was able to talk with @kalbasit who has very generously offered us a home in the github.com/go-jira org!  I now have the permissions I need for the new org, I just need to track down a human in Netflix to assist me to move the repo to the new org.

**Comment by mikepea** [comment]
Hey folks, slightly late to the party but I'm also happy to take on some PR
review responsibilities.

**Comment by coryb** [comment]
Hey @mikepea, awesome, thanks!  I have added you as a collaborator with write privs to the repo.

**Comment by ldelossa** [comment]
@coryb I'd be happy to deal with these failing test cases.

**Comment by coryb** [comment]
Hey @ldelossa I just invited you to the team.  Thanks for the offer, feel free to adjust the tests in any way that makes sense to you, they are pretty crude currently.  We do have an integration server provided to us from Atlassian, if you need further access to that let me know.

For anyone else reading this, we would love any and all extra help on the project.  I have no time for it lately as is evident from the accumulating issues and there are currently no other active maintainers.   I use the tool daily for my job, but it works for my needs so I can't justify spending much time on it currently.  We need people to help triage issues and write documentation for those frequently asked questions, as well as adding enhancements, fixing issue templates etc.  Would love to get some volunteers for triage roles and/or maintainer roles.

**Comment by ldelossa** [comment]
@coryb can you provide me with access to the cloud jira? Id like to rework the tests.

**Comment by keien** [comment]
Would be great to have a "Contributing" section in the README or something similar like other Github projects. I would love to help out as well but I'm not even sure where to get started, aside from nit-picking specific issues that I'm personally dealing with.

In my opinion this is currently the best Jira CLI out there - for the few months where this was struggling with the GDPR username issue, I spent a lot of time trying to find alternatives, and really none of them work as well as this one or have been abandoned. For the sake of the many developers out there who are forced to use Jira, I would love to have at least one CLI tool that is actively maintained.

**Comment by ldelossa** [comment]
@keien can you help confirm or deny this: https://github.com/go-jira/jira/issues/369 

Right now its not a bug for me. So a little hard to test.

**Comment by mvdan** [comment]
Sounds like this issue served its purpose and has been inactive for some time - closing.
