### ISSUE TITLE
Display subtasks for tasks that have them

### ISSUE THREAD

**Issue by agzam** [go-jira/jira#268]
Does anyone know how can I access "parent.key" in custom template for a subtask? I am trying something like:

```
{{ range .issues }}
{{ if (eq .fields.issuetype.name "Sub-task")}}{{.parent.fields.project.key}}{{end}}
```
but that's not working :(

Can anyone give me a clue how to get this?

**Comment by coryb** [comment]
It is subtle:
https://golang.org/pkg/text/template/
> When execution begins, $ is set to the data argument passed to Execute, that is, to the starting value of dot.

So Something like:
```
{{ range .issues }}
{{ if (eq .fields.issuetype.name "Sub-task")}}{{$.fields.project.key}}{{end}}
```

**Comment by agzam** [comment]
Hmm. no I think the issue is, there's no `project` field there. Maybe I should try the other way around, get the tasks and then check if they have subtasks and the display them ¯\\\_(ツ)_/¯

**Comment by agzam** [comment]
Hmm... I'm trying to get a list of tasks with subtasks like this:

    TASK-1
          SUBTASK-11
          SUBTASK-22
    TASK-2
    TASK-3
          SUBTASK-31

But it seems tasks don't carry any info about subtasks, is there any way to get this done?

**Comment by coryb** [comment]
Oh, I misunderstood your question.  I am not sure how to get this done, I think in jira task/subtask is only connected via some sort of "link" field, they won't be returned from the search in a tree like structure that you want to print.  I am not sure what property indicates if an issue is a subtask or parent task, it is probably possible to get what you want, but I suspect it will not be easy.  If you wanted to start you can use `jira list -t debug` to use the debugging template and see the entire json result.  Then you can inspect TASK-1 and SUBTASK-11 to see if there is any clear indication in there about the relationship.  You might need to add more fields via `--queryfields` in case the data is not present by default (you can generally see all the fields with `jira view TASK-1 -t debug` to dump the entire data for a specific issue).  If you can find the relationship then you would have to make a custom template to with nested loops, excluding the subtasks in the parent loop and filtering all subtasks by parent task id in the inner loop.

**Comment by agzam** [comment]
That's a ton of good info, thank you @coryb. I was able to get what I wanted, it's a bit tangled, but basically I did this:

    # in config.yml:

    custom-commands:
      - name: mine
        help: display issues assigned to me
        script: |-
          {{jira}} list --template list --query "resolution = unresolved and assignee=currentuser() and project = $JIRA_PROJECT ORDER BY priority asc, created" --queryfields="status,assignee,subtasks"

     # in templates/list

    {{ range .issues }}
    {{ .key | append ":" | printf "%-12s" }} {{ .fields.summary | printf "%-60s" }} {{ .fields.status.name | printf "%-30s" }} {{if .fields.assignee }} {{.fields.assignee.name | printf "%-12s" }} {{else}}∙{{end}} {{if .fields.subtasks}} {{range .fields.subtasks}}
    {{ "\t    " }} {{ .key | append ":" | printf "%-12s" }} {{ .fields.summary | printf "%-60s" }} {{ .fields.status.name | printf "%-30s" }}{{if .fields.assignee }} {{.fields.assignee.name | printf "%-12s" }} {{else}}∙{{end}}{{end}}{{end}}
    {{end}}
    
Now running "jira mine" displays them just like I wanted:

      SCRUM-4917:  List of users for Team Page based on both: SFDC & DB data    Code Review                     ag.ibragimov
              SCRUM-4918:  Create test plan                                             To Do                         ∙
              SCRUM-4919:  Execute test plan                                            To Do                         ∙

      SCRUM-4758:  add route                                                    In Progress                     ag.ibragimov

      SCRUM-4754:  Edit page scaffolding                                        To Do                           ag.ibragimov

**Comment by svenXY** [comment]
Nice one, thanks!

**Comment by Rahulsharma0810** [comment]
@agzam Can you nest this table format, will be really helpfull

**Comment by agzam** [comment]
I'm not sure what you mean about nesting. In any case I'm sorry, I'm not using JIRA at my new gig, could say something that I won't be able to confirm.

**Comment by Rahulsharma0810** [comment]
I mean implement this in table template, instead of list template
