### ISSUE TITLE
Cut a new release for modules support?

### ISSUE THREAD

**Issue by mikepea** [go-jira/jira#274]
Hey @coryb  - mind if I tag master with the 1.0.21 version, so we've got a real release with modules supported?

**Comment by coryb** [comment]
yeah, sounds good.  I have been meaning to do this for a while.
It has been a while, but I think the release process is:
```
# creates a ./jira binary used later to extract current usage
make

# make all the cross platform binaries, requires docker
make all

# update the CHANGELOG.md
make update-changelog

# update README, create git tag, and push to github
make release
```
Then I copy/paste the changelog snippet into https://github.com/go-jira/jira/releases/new
and attach all the cross platforms binaries in the ./dist directory

Let me know if you run into problems.

**Comment by mikepea** [comment]
The 'make all' step doesn't seem to be working for me at least:

````
Checking for required docker image karalabe/xgo-latest... found.
Cross compiling ....
Building locally ....
Compiling for linux/386...
can't load package: package .: no Go files in /
2019/09/14 22:53:47 Failed to cross compile package: exit status 1.
make: *** [all] Error 1
````

I'm not sure how to get this working

**Comment by coryb** [comment]
Could you try the `make all` again?  I updated the Makefile target to use a fork of xgo more actively supported and theoretically has go module support.

**Comment by mikepea** [comment]
Looks like it works! I've cut the v1.0.21 release - the Makefile process was a little flakey due to NEWVER and CURVER not being calculated correctly (something to do with the v1.0.20 tag?), but I think I've gotten around that by setting them as variables on the command line:

````
CURVER=1.0.20 NEWVER=1.0.21 make update-changelog
CURVER=1.0.20 NEWVER=1.0.21 make release
````

**Comment by coryb** [comment]
Nice, yeah the CURVER and NEWVER can get messed up if you previously ran the release process and it fails somewhere in the middle (after the git tag is applied).  Glad you got it working!

**Comment by ldelossa** [comment]
hey @coryb @mikepea 

I can't do the final step of pushing to master: 
```
❯ git push origin master 
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 622 bytes | 622.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Waiting on code owner review from coryb, ldelossa, and/or mikepea.
To github.com:go-jira/jira.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:go-jira/jira.git'
```

**Comment by coryb** [comment]
Odd, I have removed the code review restriction, I guess I never noticed since it ignores admins.  You should be able to push the changes now.
