### ISSUE TITLE
jiracli.findClosestParentPath is broken with figtree v1.0.0

### ISSUE THREAD

**Issue by mikepea** [go-jira/jira#277]
Somehow I managed to update the go.mod to use coryb/figtree v1.0.0 -- I think this happened kinda naturally, since the current specified version is pinned to v0.0.0-{commit}.

There's a difference in the function signature, that results in an error:

```
jiracli/util.go:29:34: too many arguments in call to figtree.FindParentPaths
```

**Comment by coryb** [comment]
fixed in #278
