### ISSUE TITLE
prebuild versions of 1.0.21 does not look like correct builds

### ISSUE THREAD

**Issue by henrik-farre** [go-jira/jira#279]
If I download https://github.com/go-jira/jira/releases/download/v1.0.21/jira-linux-amd64 it is only 354K big, and `file jira-linux-amd64` says:

jira-linux-amd64: current ar archive

It does not work to chmod +x the file and try to run it :)

**Comment by vabue** [comment]
Same with the windows versions. 355KB and "This app can't run on your PC".

**Comment by mikepea** [comment]
We used a new fork of `xgo` to make the builds, and tbh I did not think to
test them directly. Whoops!

I'll take a look later today (and add some tests to make sure they work in
future!)

**Comment by mikepea** [comment]
I've updated with new versions built using gox rather than xgo -- they appear to be working for me, but please test and let me know if you have problems. I don't have a windows box to test against.

**Comment by henrik-farre** [comment]
Works for me :)
