### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by estensen** [go-jira/jira#291]
The instructions for building and installing doesn't work
```
~ go get github.com/go-jira/jira/cmd/jira
# github.com/go-jira/jira/jiracli
go/src/github.com/go-jira/jira/jiracli/usage.go:157:45: cannot use app (type *"gopkg.in/alecthomas/kingpin.v2".Application) as type *"github.com/coryb/kingpeon/vendor/gopkg.in/alecthomas/kingpin.v2".Application in argument to kingpeon.RegisterDynamicCommandsWithRunner
```

Running macOS Catalina 10.15.1 Beta

**Comment by pdecat** [comment]
Had the same issue, it was caused by old content in `GOPATH`.

Work-around (tested only with go 1.13.3 on Ubuntu), clone then build:
```
# go get -d -u github.com/go-jira/jira/cmd/jira
# cd $(go env GOPATH)/src/github.com/go-jira/jira/cmd/jira
# go install
```

**Comment by jamesog** [comment]
Turning on modules mode explicitly seems to make it work:

```
GO111MODULE=on go get github.com/go-jira/jira/cmd/jira
```

This is the same effect as running `go install` inside `$GOPATH/src/github.com/go-jira/jira/cmd/jira` as @pdecat suggests above.

@mikepea is this a side-effect of ba7cc1314580869001ceac124e881799b7f3ebfa where you switched away from gopkg.in to use modules?

**Comment by dlo** [comment]
@jamesog Thank you! This did it.

**Comment by izissise** [comment]
After trying with both suggested fix or reverting the mentionned commit, I'm still left with the same issue:
```
$ go version && make
go version go1.10.4 linux/amd64
go build -gcflags="-e" -v -ldflags "-w -s" -o '$HOME/go/src/github.com/go-jira/jira/jira' cmd/jira/main.go
github.com/go-jira/jira/jiracli
# github.com/go-jira/jira/jiracli
jiracli/usage.go:157:45: cannot use app (type *"gopkg.in/alecthomas/kingpin.v2".Application) as type *"github.com/coryb/kingpeon/vendor/gopkg.in/alecthomas/kingpin.v2".Application in argument to kingpeon.RegisterDynamicCommandsWithRunner
Makefile:24: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by jamesog** [comment]
@izissise that's a very old version of Go and no longer supported. I recommend you upgrade to the latest 1.14 release.

Go modules are only since 1.11.

**Comment by izissise** [comment]
I guess I'll have to upgrade to ubuntu 20.04 sooner than later then,
Thanks for the reply :)
