### ISSUE TITLE
ERROR Invalid Usage: template: gojira:22:50: executing "gojira" at <.name>: can't evaluate field name in type interface {}

### ISSUE THREAD

**Issue by svenXY** [go-jira/jira#304]
the above error occurs when using `jira view PROJ-123`.

It cannot resolve the watchers in the view-template. I found customfield_10110 or similar in the code, but here it is a different field (which can be the case for different jira installations, I know). When trying to fix it, I tried recompiling with the field adjusted, but to no avail.

Any idea what to do to fix it?

Thanks,
Sven

**Comment by coryb** [comment]
This is just a template issue, you can export templates and customize.  I am not sure what `customfield_10110` is for your install but it seems different than what I am used to.  To see all the available fields you can just dump it is a json with: `jira view PROJ-123 -t json`

You can also export templates and modify if to your needs with:
```
jira export-templates -t view
```
that will write ~/.jira.d/templates/view
then you can just edit the template to remove the relevant section:
```
{{if .fields.customfield_10110 -}}
watchers: {{ range .fields.customfield_10110 }}{{ .name }} {{end}}
{{end -}}
```

**Comment by svenXY** [comment]
Hi @coryb , thanks for the answer. I had done this alreadyand yes, for me it is a different customfield that holds the watchers. Furthermore, you do not get a structure to take .name from, so for me it boiled down to:

```
{{if .fields.customfield_13831 -}}
watchers: {{ range .fields.customfield_13831 }}{{ . | printf "%s" | regReplace "(.+)\\(.*" "$1, " }} {{end}}
{{end -}}
```
