### ISSUE TITLE
How to login?

### ISSUE THREAD

**Issue by k0pernikus** [go-jira/jira#312]
I installed go-jira via:

```
GO111MODULE=on go get github.com/go-jira/jira/cmd/jira
```

I have setup my basic ~/.jira.d/config.yml with an endpoint. I expect to be prompted for credentials, yet I see on a notice after `jira login`:

```
NOTICE No need to login when using api-token authentication method
```

I am not aware of having setup any api-token authentication method. What am I doing wrong?

**Comment by k0pernikus** [comment]
It helps to completely read the [README.md](https://github.com/go-jira/jira#authentication). I had to add the endpoint, user (email address), and I must create a token at:

https://id.atlassian.com/manage/api-tokens

I went for the less secure option to:

    export JIRA_API_TOKEN=$MY_CREATED_TOKEN

The login command is obsolete and I can just use any command as it will connect by itself, e.g. 

    jira list

**Comment by metov** [comment]
I did read the readme but was still confused - thank you for explaining this concisely and clearly.

It would be helpful to put some idiot proof basic login instructions (like https://github.com/go-jira/jira/issues/312#issuecomment-580390357) right after the install section. A new user's first question is, "Does this even work properly?" -- until they can get correct output from `jira list`, none of the details in the readme are useful or relevant.
