### ISSUE TITLE
jira create stopped working

### ISSUE THREAD

**Issue by rattboi** [go-jira/jira#333]
Getting the following since yesterday:

```
MacBook-Pro :: ~ % jira create                                                                                                                                                           
ERROR The query parameter 'username' is not supported in GDPR strict mode.
? Jira reported an error, edit again? (Y/n) 
```

my config.yaml has the following:
```
endpoint: https://<work>.atlassian.net                                                                                                                                               
user: rattboi                                                                                                                                                                   
login: <my work email>                                                                                                                                                      
jira-deployment-type: cloud                                                                                                                                                           password-source: keyring                                                                                                                                                              
issuetype: Story                                                                                                                                                                      
project: IO                                                                                                                                                                           
priority: P2       
```

I'm running latest release: 1.0.23

**Comment by jrabek** [comment]
Maybe an update is needed to https://github.com/go-jira/jira/pull/317?

**Comment by wolgastj** [comment]
Similar seems to be happening with `jira assign` and `jira take`

**Comment by jtomaszewski** [comment]
Yeah, it started happening today/yesterday. Seems like Atlassian has changed something again in their APIs and now fix from the https://github.com/go-jira/jira/pull/317 is not enough anymore.

**Comment by BorysDrozhak** [comment]
Wondering if there anyone already created a PR to fix it

**Comment by nvgoldin** [comment]
Same here

**Comment by zenspider** [comment]
Oddly... I just had this happen mid-create. I'd created a couple test tix. Deleted them. And then couldn't create the ones I actually wanted to create because of this error. Running with `-vvv` shows that it is getting caught up on that `search?username` query (oddly enough, for myself! the privacy violations!).

oooh... I was changed to administrator! that might be it!

**Comment by zenspider** [comment]
Go is not my strongpoint... but I got into the code. Ironically, the GDPR violation is happening inside of `fixGDPRUserFields`:

```
(dlv) p opts
*github.com/go-jira/jira.UserSearchOptions {
        Query: "",
        Username: "ryan.davis@zendesk.com",
        AccountID: "",
        StartAt: 0,
        MaxResults: 0,
        Property: "",}
(dlv) stack
 0  0x00000000015fc48b in github.com/go-jira/jira.UserSearch
    at ./users.go:23
 1  0x00000000016221b4 in github.com/go-jira/jira/jiracmd.fixUserField
    at ./jiracmd/edit.go:184
 2  0x0000000001622dae in github.com/go-jira/jira/jiracmd.fixGDPRUserFields
    at ./jiracmd/edit.go:232
 3  0x000000000163c8c1 in github.com/go-jira/jira/jiracmd.CmdCreate.func1
    at ./jiracmd/create.go:99
 4  0x0000000001601aee in github.com/go-jira/jira/jiracli.EditLoop
    at ./jiracli/cli.go:466
 5  0x000000000161d2f8 in github.com/go-jira/jira/jiracmd.CmdCreate
    at ./jiracmd/create.go:97
...
```

**Comment by zenspider** [comment]
According to the JIRA REST docs, you don't need to have an assign field to create a ticket, so this should be entirely avoidable by just not doing it, no?

**Comment by endorama** [comment]
Hello, I had this issue today while creating a new issue. My case was related to the `reporter` field (which is mandatory it seems), that in the YAML template is:

```yaml
fields:
  reporter:
    name: f.bar
```

I've been able to fix it by replacing `name` with `id`, taking my account number from the profile page URL (as in https://community.atlassian.com/t5/Jira-questions/where-can-i-find-my-Account-ID/qaq-p/976527).

It's really painful clearly, so I'll be looking around for a better solution.

PS: thanks for the work that went into this CLI, it really shines :+1:

**Comment by bradym** [comment]
Just figured out a workaround by editing templates.

Looking at the template used by the create command you'll see:

```
  reporter:
    name: {{ or .overrides.reporter .overrides.user }}
```

Replace `name` with `id` so it becomes:

```
  reporter:
    id: {{ or .overrides.reporter .overrides.user }}
```

Now in your config.yml set the override:

```
overrides:
  reporter: <your user id here>
```

And you should be set! There may be other templates that need to be modified as well, I'll take a look and take a crack at a PR.

**Comment by ldelossa** [comment]
@bradym I just merged this: https://github.com/go-jira/jira/pull/364

which removes the username issues. can you please see if issue is still preset? 
I did not take into account any templates, so it maybe necessary to still move the template stuff around make it all correct. I have not used templates yet

**Comment by ldelossa** [comment]
I just released https://github.com/go-jira/jira/releases/tag/v1.0.24

This should fix these issues. If it does not "@" me and I will re-open this ticket.

**Comment by bradym** [comment]
@ldelossa - Just tried to run `jira create` without any custom templates, and I got the same error:

```
$ jira create
ERROR The query parameter 'username' is not supported in GDPR strict mode.
? Jira reported an error, edit again? (Y/n) 
```

**Comment by ldelossa** [comment]
@bradym are you sure you are using: 

Are you sure you are running the latest binary from here: https://github.com/go-jira/jira/releases/tag/v1.0.24 ? 

I am not facing this issue.

**Comment by bradym** [comment]
@ldelossa - you're right, I was not running latest due to a $PATH issue.
 
However, now I'm getting a different error:

```
$ jira create
ERROR reporter: Reporter is required.
```

I'm not using any custom templates (I've renamed my $HOME/.jira.d/templates folder to make sure) and here's the yaml I tried to use:

```
fields:
  project:
    key: TST
  issuetype:
    name: Bug 
  summary: >-
    This is a testing issue
  priority: 
    name: P4
  description: |~
    Just testing
  assignee:
    name: 
  reporter:
    name: bradym
```

**Comment by ldelossa** [comment]
okay that issues dups: https://github.com/go-jira/jira/issues/369

closing this and lets track that problem in 369

**Comment by jaymzh** [comment]
I'm still getting this on 1.0.26.

```
[phil@ldt-hardwired bin]$ jira create
ERROR reporter: Account ID phil@vicarious.com does not exist.
```

**Comment by jaymzh** [comment]
Oh, sorry misread that last comment, this is being tracked in the other ticket. Ignore my comment. Apologies.
