### ISSUE TITLE
RFE: Showing issues' related github commits

### ISSUE THREAD

**Issue by schnoddelbotz** [go-jira/jira#73]
I was wondering whether you'd be willing to include support for retrieving github commits that are related to a JIRA Issue.

Connecting JIRA to github is [outlined here](https://confluence.atlassian.com/adminjiracloud/connect-jira-cloud-to-github-814188429.html) but unfortunately the [REST API to retrieve commit details](https://answers.atlassian.com/questions/32535478/get-commits-info-of-a-jira-issue-using-rest-api) is private/undocumented -- but nevertheless works fine.

As far as I can see this would require introduction of a 'static' schema -- would that be acceptable?
Ideally, listing tickets would allow optional inclusion of commits, merge status, peer review...
I'd happily try to work on it and create a PR but wanted to hear your general thoughts on this first.

btw, thanks a lot for go-jira. It already rocks :)

**Comment by coryb** [comment]
Hey Jan, sorry I didnt have time to reply to this when I saw it, then I forgot to reply after.

I am generally okay adding features for undocumented apis, as long as they works.  I would want to make sure it works with the atlassian.net hosted jira service, which is what my regression tests work against.  I am not sure how we would test that, but in theory we could set up issues/PRs on a test branch tor this project to test it out.

The code is very messy and uses many bad practices (like casting interface{} all over).  I need to fix that, but am short on time.  I am concerned about keeping the command line interface simple, so we might need to discuss any changes to the CLI usage.  If you want to work towards a PR that would be great, I will unlikely have time to deal with this feature myself.

Thanks!
-Cory

**Comment by schnoddelbotz** [comment]
Hi Cory,

thanks for your response and sorry for my late reply now.

I've made a first attempt to tweak code to make it work as outlined. We're using atlassian.net hosted jira service, so this shouldn't be a problem. Just to explain my goal: In the end, I'd like to produce changelog messages in MarkDown format -- that link to our JIRA issue and corresponding github PRs.

My (relatively small...) tweaks are referenced above.

I believe it's not really ready for a PR yet... please let me know how to improve... or just cherry-pick whatever looks usable to you. I must admit I have no clue how to make the github-integration
optional, so that the 2nd request only happens if people effectively use the JIRA github integration (prefs? cli-option?).

Having the changes applied, output currently looks like this:
```
...existing defaultViewTemplate stuff... then, new at bottom:

 PullRequest: id=#3048, status=MERGED, lastUpdate=2017-05-15T12:42:26.000+0200
 PullRequest: id=#3056, status=MERGED, lastUpdate=2017-05-12T11:43:30.000+0200

changelog:
[Story] [SPR-1537](https://myendpoint.atlassian.net/browse/SPR-1537) Implement logic to foobar  #3048 #3056
```

Please let me know how to proceed. Cheers!

**Comment by coryb** [comment]
Hey, sorry again, you have good timing as your last comment got to me as I was leaving the country for a 3 week vacation, then lost track :)  Anyway, the changes look interesting but agree we need to figure out a strategy to make them optional.  I wonder if there is some information in the issue metadata that indicates that github integration is enabled.

If you run `jira view <ISSUE> -t debug` that will print the full json output for what is available to the view template.  I wonder if there is any field in there that indicates there is some relation to github.

**Comment by coryb** [comment]
I have completely rewritten gojira, so it might be easier for you to hack on now if you want to send the PR my way.  I dont have a source of JIRA-Github integrations to work with so I cant provide much assistance on this one.

**Comment by schnoddelbotz** [comment]
I am sorry for the long silence on this one. In the meantime, I switched jobs and also don't have access to a Jira instance with github integration.
As nobody else jumped in here, I'd think it's okay to close the issue for now. If somebody else sees the need for this and/or could sponsor a test/dev instance, it could still be re-opened...?
